on: push

name: rust check package install

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
    - run: cd rust && python3 -m pip install . --use-feature=in-tree-build
